<a href="https://colab.research.google.com/github/Pritishcoder07/BasicML/blob/main/Basic_ML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NUMPY


#  Array Creation with Numpy


**Conversion from other Python structures (e.g., lists, tuples)**

In [1]:
import numpy as np

In [2]:
listarray = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [3]:
listarray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
listarray.shape


(3, 3)

In [5]:
listarray.dtype

dtype('int64')

In [6]:
listarray[0,1]=10

In [7]:
listarray

array([[ 1, 10,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [8]:
listarray.size

9

In [9]:
Heloo = np.array([[1,2,8,7,6,50,56]])

In [10]:
Heloo[0,1]=55

In [11]:
Heloo


array([[ 1, 55,  8,  7,  6, 50, 56]])

**Intrinsic numpy array array creation objects (e.g., arange, ones, zeros, etc.)**

In [12]:
zeros = np.zeros([2,15])


In [13]:
zeros

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [14]:
range =np.arange(20)

In [15]:
range

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [16]:
lspace = np.linspace(1,5,12)
lspace

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

** BASICS ML ATTRIBUTE **

In [17]:
arr = ([1,2,3],[4,5,6],[7,8,9])
arr

([1, 2, 3], [4, 5, 6], [7, 8, 9])

In [18]:
arr2 = np.array(arr)

In [19]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
arr2.sum(axis=0)

array([12, 15, 18])

In [21]:
arr2.sum(axis=1)

array([ 6, 15, 24])

In [22]:
arr2.argmax()


np.int64(8)

In [23]:
arr2.argmin()

np.int64(0)

In [24]:
arr2.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [25]:
arr2.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [26]:
arr2.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
arr2.reshape((9,1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [28]:
total =listarray+arr2

In [29]:
total

array([[ 2, 12,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [30]:
total2 =total *2
total2

array([[ 4, 24, 12],
       [16, 20, 24],
       [28, 32, 36]])

In [31]:
np.sqrt(total2)

array([[2.        , 4.89897949, 3.46410162],
       [4.        , 4.47213595, 4.89897949],
       [5.29150262, 5.65685425, 6.        ]])

# PANDAS


In [32]:
import pandas as pd


In [33]:
dict1 ={
    "name":['harry','rohan','skillf','shubh'],
    "marks":[92,34,24,30],
    "city":['rampur','kolkata','bareilly','antartica']
}

In [34]:
df = pd.DataFrame(dict1)
df



name  marks       city
0   harry     92     rampur
1   rohan     34    kolkata
2  skillf     24   bareilly
3   shubh     30  antartica

In [35]:
df.to_csv('hello.csv')


In [36]:
df.to_csv('friends.csv',index=False)

In [37]:
df.head(1)


name  marks    city
0  harry     92  rampur

In [38]:
df.tail(2)

name  marks       city
2  skillf     24   bareilly
3   shubh     30  antartica

In [39]:
df.describe()

marks
count   4.000000
mean   45.000000
std    31.601688
min    24.000000
25%    28.500000
50%    32.000000
75%    48.500000
max    92.000000

In [40]:
newdf = pd.DataFrame(np.random.rand(10000))


In [41]:
type(newdf)

pandas.core.frame.DataFrame

In [42]:
newdf.dtypes

0    float64
dtype: object

In [43]:
newdf

0
0     0.531623
1     0.310205
2     0.203796
3     0.551447
4     0.694038
...        ...
9995  0.619399
9996  0.932851
9997  0.004392
9998  0.655677
9999  0.742762

[10000 rows x 1 columns]