<a href="https://colab.research.google.com/github/Pritishcoder07/BasicML/blob/main/Basic_ML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NUMPY


#  Array Creation with Numpy


**Conversion from other Python structures (e.g., lists, tuples)**

In [2]:
import numpy as np

In [3]:
listarray = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [4]:
listarray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
listarray.shape


(3, 3)

In [6]:
listarray.dtype

dtype('int64')

In [7]:
listarray[0,1]=10

In [8]:
listarray

array([[ 1, 10,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [9]:
listarray.size

9

In [10]:
Heloo = np.array([[1,2,8,7,6,50,56]])

In [11]:
Heloo[0,1]=55

In [12]:
Heloo


array([[ 1, 55,  8,  7,  6, 50, 56]])

**Intrinsic numpy array array creation objects (e.g., arange, ones, zeros, etc.)**

In [13]:
zeros = np.zeros([2,15])


In [14]:
zeros

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [15]:
range =np.arange(20)

In [16]:
range

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [17]:
lspace = np.linspace(1,5,12)
lspace

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

** BASICS ML ATTRIBUTE **

In [18]:
arr = ([1,2,3],[4,5,6],[7,8,9])
arr

([1, 2, 3], [4, 5, 6], [7, 8, 9])

In [19]:
arr2 = np.array(arr)

In [20]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
arr2.sum(axis=0)

array([12, 15, 18])

In [22]:
arr2.sum(axis=1)

array([ 6, 15, 24])

In [23]:
arr2.argmax()


np.int64(8)

In [24]:
arr2.argmin()

np.int64(0)

In [25]:
arr2.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [26]:
arr2.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [27]:
arr2.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
arr2.reshape((9,1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [29]:
total =listarray+arr2

In [30]:
total

array([[ 2, 12,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [31]:
total2 =total *2
total2

array([[ 4, 24, 12],
       [16, 20, 24],
       [28, 32, 36]])

In [32]:
np.sqrt(total2)

array([[2.        , 4.89897949, 3.46410162],
       [4.        , 4.47213595, 4.89897949],
       [5.29150262, 5.65685425, 6.        ]])

# PANDAS


In [33]:
import pandas as pd


In [34]:
dict1 ={
    "name":['harry','rohan','skillf','shubh'],
    "marks":[92,34,24,30],
    "city":['rampur','kolkata','bareilly','antartica']
}

In [35]:
df = pd.DataFrame(dict1)
df



name  marks       city
0   harry     92     rampur
1   rohan     34    kolkata
2  skillf     24   bareilly
3   shubh     30  antartica

In [36]:
df.to_csv('hello.csv')


In [37]:
df.to_csv('friends.csv',index=False)

In [38]:
df.head(1)


name  marks    city
0  harry     92  rampur

In [39]:
df.tail(2)

name  marks       city
2  skillf     24   bareilly
3   shubh     30  antartica

In [40]:
df.describe()

marks
count   4.000000
mean   45.000000
std    31.601688
min    24.000000
25%    28.500000
50%    32.000000
75%    48.500000
max    92.000000

In [41]:
newdf = pd.DataFrame(np.random.rand(10000))


In [42]:
type(newdf)

pandas.core.frame.DataFrame

In [43]:
newdf.dtypes

0    float64
dtype: object

In [44]:
newdf

0
0     0.015542
1     0.913915
2     0.874715
3     0.191097
4     0.461760
...        ...
9995  0.575369
9996  0.796163
9997  0.860529
9998  0.545545
9999  0.660391

[10000 rows x 1 columns]

# DATA CLEANING

In [45]:
import pandas as pd


In [46]:
from google.colab import files
upload  = files.upload()

Saving dirty_dataset_1000.csv to dirty_dataset_1000.csv


In [47]:
messdata = pd.read_csv('dirty_dataset_1000.csv')

In [48]:
messdata



Name     Age  Gender    City Salary        Date  \
0     Deborah Anderson     200    Male  Mumbai  82481  2021-04-16   
1                  NaN      16    Male  Bhopal    50k  2024-01-09   
2            James Liu  twenty  Female   Delhi  90438  2023-02-10   
3           Aaron Ford     200     NaN  Bhopal   -inf  2024-11-07   
4        Andrea Mercer       0     NaN  Nagpur  62322  2023-08-05   
...                ...     ...     ...     ...    ...         ...   
1015      Robert Gibbs      19  Female  Bhopal  32982  2021-08-29   
1016       Steven Peck     200    Male  Nagpur    inf  2021-07-16   
1017       Steve Munoz  twenty     NaN  Bhopal   -inf  32-13-2020   
1018         Zoe Black     NaN       F     NaN  69566  2023-11-29   
1019     Benjamin West     NaN    Male     NaN    NaN  2023-10-14   

                   Phone  Marks Passed  
0                    NaN   30.0    NaN  
1                    NaN  -20.0    Yes  
2     651-509-7684x87571  150.0   True  
3             0002108269  -20.0    Yes  
4             0006512234    NaN     No  
...                  ...    ...    ...  
1015          0005006861    NaN   True  
1016                 NaN    NaN    Yes  
1017                 NaN   45.0  False  
1018                 NaN    NaN  False  
1019                 NaN   92.0    NaN  

[1020 rows x 9 columns]

In [49]:
messdata.head(13)

Name     Age  Gender    City Salary        Date  \
0      Deborah Anderson     200    Male  Mumbai  82481  2021-04-16   
1                   NaN      16    Male  Bhopal    50k  2024-01-09   
2             James Liu  twenty  Female   Delhi  90438  2023-02-10   
3            Aaron Ford     200     NaN  Bhopal   -inf  2024-11-07   
4         Andrea Mercer       0     NaN  Nagpur  62322  2023-08-05   
5          Anthony Cruz     200       F  Bhopal    inf  2024-12-16   
6          Hannah Dixon     NaN     NaN  Nagpur   -inf  2024-12-13   
7       Jennifer Hayden     NaN     NaN  Bhopal    NaN  2025-10-02   
8         Daniel Thomas  twenty    Male  Raipur    inf  2022-12-14   
9           Sean Guzman     NaN       M  Mumbai  98541  2023-12-27   
10         Raymond Lara     200  Female     NaN    50k  2021-10-24   
11           John Brown      42       F     NaN    50k  2023-05-12   
12  Mr. Dennis Benjamin     NaN     NaN  Nagpur  17906  2023-02-11   

                 Phone  Marks Passed  
0                  NaN   30.0    NaN  
1                  NaN  -20.0    Yes  
2   651-509-7684x87571  150.0   True  
3           0002108269  -20.0    Yes  
4           0006512234    NaN     No  
5           0001672450    1.0   True  
6    (834)239-1491x362  -20.0     No  
7                  NaN    NaN    Yes  
8        (708)542-0995  -20.0     No  
9                  NaN    NaN    NaN  
10          0007903205   46.0  False  
11  703.468.0098x47042   61.0    NaN  
12                 NaN    NaN  False

In [50]:
messdata.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 9 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Name    963 non-null    object 
 1   Age     769 non-null    object 
 2   Gender  697 non-null    object 
 3   City    767 non-null    object 
 4   Salary  824 non-null    object 
 5   Date    1020 non-null   object 
 6   Phone   483 non-null    object 
 7   Marks   753 non-null    float64
 8   Passed  653 non-null    object 
dtypes: float64(1), object(8)
memory usage: 71.8+ KB


In [51]:
messdata.isnull().sum()/len(messdata)*100

Name       5.588235
Age       24.607843
Gender    31.666667
City      24.803922
Salary    19.215686
Date       0.000000
Phone     52.647059
Marks     26.176471
Passed    35.980392
dtype: float64

In [52]:
messdata['Name'].fillna('NAN',inplace=True)

/tmp/ipython-input-1900140915.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  messdata['Name'].fillna('NAN',inplace=True)


In [53]:
messdata['Age'] = pd.to_numeric(messdata['Age'], errors='coerce')

In [54]:
messdata.loc[messdata['Age'] < 0, 'Age'] = np.nan

In [55]:
messdata.loc[messdata['Age'] > 100, 'Age'] = np.nan

In [56]:
messdata['Gender'].fillna('NAN',inplace=True)

/tmp/ipython-input-3498200669.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  messdata['Gender'].fillna('NAN',inplace=True)


In [57]:
messdata['City'].fillna('NAN',inplace=True)

/tmp/ipython-input-3607804485.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  messdata['City'].fillna('NAN',inplace=True)


In [58]:
print('hello')

hello


In [59]:
messdata.head(13)

Name   Age  Gender    City Salary        Date  \
0      Deborah Anderson   NaN    Male  Mumbai  82481  2021-04-16   
1                   NAN  16.0    Male  Bhopal    50k  2024-01-09   
2             James Liu   NaN  Female   Delhi  90438  2023-02-10   
3            Aaron Ford   NaN     NAN  Bhopal   -inf  2024-11-07   
4         Andrea Mercer   0.0     NAN  Nagpur  62322  2023-08-05   
5          Anthony Cruz   NaN       F  Bhopal    inf  2024-12-16   
6          Hannah Dixon   NaN     NAN  Nagpur   -inf  2024-12-13   
7       Jennifer Hayden   NaN     NAN  Bhopal    NaN  2025-10-02   
8         Daniel Thomas   NaN    Male  Raipur    inf  2022-12-14   
9           Sean Guzman   NaN       M  Mumbai  98541  2023-12-27   
10         Raymond Lara   NaN  Female     NAN    50k  2021-10-24   
11           John Brown  42.0       F     NAN    50k  2023-05-12   
12  Mr. Dennis Benjamin   NaN     NAN  Nagpur  17906  2023-02-11   

                 Phone  Marks Passed  
0                  NaN   30.0    NaN  
1                  NaN  -20.0    Yes  
2   651-509-7684x87571  150.0   True  
3           0002108269  -20.0    Yes  
4           0006512234    NaN     No  
5           0001672450    1.0   True  
6    (834)239-1491x362  -20.0     No  
7                  NaN    NaN    Yes  
8        (708)542-0995  -20.0     No  
9                  NaN    NaN    NaN  
10          0007903205   46.0  False  
11  703.468.0098x47042   61.0    NaN  
12                 NaN    NaN  False

In [1]:
print ('hello')

hello
