<a href="https://colab.research.google.com/github/Pritishcoder07/BasicML/blob/main/NUMPY.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NUMPY


Video 1 Basic Numpy

----------------------------------
NumPy Creation & Initializing

---------------------------------

In [61]:
# IMPORT NUMPY AS NP
import numpy as np

In [62]:
# import dataset 1D Array |  1D Array is also know as Vector
a = np.array([1,5,2,1])
print((a))

[1 5 2 1]


Q. Using numpy array in the front of list

A. Because perform all NumPy operations efficiently, use a NumPy array, not a regular Python list.

In [63]:
# import dataset 2D Array | 2D Array is also know as Matrix
b = np.array([[1,5,6,2],[1,5,6,2]])
print(b)


[[1 5 6 2]
 [1 5 6 2]]


In [64]:
# import dataset 3D Array or Higher Array \ 3D Array or Higher Array is konw as tensor
c = np.array([[[1,1,1,1],[1,1,1,2]],[[1,1,1,3],[1,1,1,4]]])
print(c)

[[[1 1 1 1]
  [1 1 1 2]]

 [[1 1 1 3]
  [1 1 1 4]]]


In [65]:
# Data Type \ ( dtype )
A = np.array([5,9,6,3,5],dtype=int)
B = np.array([5,9,6,3,5],dtype=float)
C = np.array([5,9,6,3,5],dtype=str)
D = np.array([5,9,6,3,5],dtype=bool)
E = np.array([5,9,6,3,5],dtype=complex)
print(A)
print(B)
print(C)
print(D)
print(E)


[5 9 6 3 5]
[5. 9. 6. 3. 5.]
['5' '9' '6' '3' '5']
[ True  True  True  True  True]
[5.+0.j 9.+0.j 6.+0.j 3.+0.j 5.+0.j]


see i can change the datatype of array to any datatype

In [66]:
# Data Arange
A = np.arange(1,11)
print(A)


[ 1  2  3  4  5  6  7  8  9 10]


In [67]:
B = np.arange(1,100,5)
print(B)

[ 1  6 11 16 21 26 31 36 41 46 51 56 61 66 71 76 81 86 91 96]


Cell 1 -> arange: Creates a NumPy array with evenly spaced values within a specified range.

Cell 2 -> it is written (1,100,5) The 5 after 100 means the gap between the numbers


In [68]:
# Data Resape
A = np.arange(1,11).reshape(2,5)
print(A)
B = np.arange(1,13).reshape(3,4)
print(B)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


Reshape : Changes the shape (dimensions) of a NumPy array without changing its data. it's vaild only reshape like (2,5),(3,5) like multiple vaild only

In [69]:
# ONES \ ( np.ones )
A = np.ones((3,4))
print(A)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


All Cell baiscally for initializing the value without any think for Neural Network

Cell 1 -> Ones : Creates a NumPy array filled with 1s.

In [70]:
# Zeros \ ( np.zeros )
A = np.zeros((3,4))
print(A)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


Cell 2 -> Zeros : Creates a NumPy array filled with 0s.


In [71]:
# Random \  (np.random.random )
A = np.random.random((3,4))
print(A)

[[0.5311368  0.55624269 0.42313895 0.55414157]
 [0.44116079 0.87188976 0.02150362 0.05193088]
 [0.24209018 0.79856579 0.16585587 0.0039428 ]]


Cell 3 -> Random : Creates a NumPy array with random values between 0 and 1

In [72]:
# linespace \ ( np.linspace )
A = np.linspace(1,15,9)
print(A)

[ 1.    2.75  4.5   6.25  8.    9.75 11.5  13.25 15.  ]


Linspace : Creates a NumPy array with evenly spaced values between a start and an end value. After the 15 9 means total number you will seprate


In [73]:
# Indetity \ ( np.indetity )
A = np.identity(5)
print(A)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


Identity : Creates an identity matrix with 1s on the main diagonal and 0s elsewhere.

## Summary of NumPy Operations

This notebook provides an introduction to fundamental NumPy array creation and manipulation techniques:

*   **Array Creation:**
    *   `np.array()`: Used to create 1D (vectors), 2D (matrices), and higher-dimensional arrays (tensors) from Python lists.
    *   `dtype`: Allows explicit specification of data types for array elements (e.g., `int`, `float`, `str`, `bool`, `complex`).
    *   `np.arange()`: Creates arrays with evenly spaced values within a given range, with an optional step size.
    *   `np.linspace()`: Creates arrays with a specified number of evenly spaced values between a start and end point.

*   **Special Array Initialization:**
    *   `np.ones()`: Creates arrays filled with ones.
    *   `np.zeros()`: Creates arrays filled with zeros.
    *   `np.random.rand()`: Creates arrays with random values between 0 and 1.
    *   `np.identity()`: Creates an identity matrix (square matrix with ones on the main diagonal and zeros elsewhere).

*   **Array Manipulation:**
    *   `.reshape()`: Changes the shape (dimensions) of an array without altering its data, provided the total number of elements remains the same.

In [74]:
print("HI")

HI


-------------------------------------------
NumPy Attributes

-------------------------------------------

In [75]:
a1 = np.arange(10)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

print(a1)
print(a2)
print(a3)

[0 1 2 3 4 5 6 7 8 9]
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [76]:
# ndim \ ( ndim )

a1 = np.arange(10)
a1.ndim


1

Ndim : Returns the number of dimensions (axes) of a NumPy array.

In [77]:
# shape \ ( shape )

a1 = np.arange(10)
a2.shape

(3, 4)

In [78]:
a3.shape

(2, 2, 2)

Shape: Returns the shape (rows, columns, and dimensions) of a NumPy array.

(2, 2, 2) → 2 Dimension , each containing 2 rows and 2 columns.

In [79]:
# size \ ( size )
a1 = np.arange (10)
a1.size

10

Size: Returns the total number of elements in a NumPy array.

In [80]:
# itemsize \ ( itemsize )

a1 = np.arange(10)
a1.itemsize

8

Itemsize: Returns the size of each element in a NumPy array in bytes.

In [81]:
# dtypw \ ( dtype )

a1 = np.arange(10)
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int64
float64
int64


Dtype: Returns the data type of the elements in a NumPy array.

---------------------------------------------------------
Changing Datatype

--------------------------------------------------------

In [82]:
# Change Datatype | ( as.type )

a1 = np.arange(10)
a1.astype(np.int32)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)

---------------------------
Arithmetic operations

---------------------------

In [83]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

print(a1)

print(a2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


Both are Scalar Opeartion - Performs a mathematical operation between each element of a NumPy array and a single value (scalar)

Cell 1 (Arithmetic operation)

Cell 2 (Relational operation)

In [84]:
# Arithmetic \ ( a1 + - * / % ** )

a1+2


array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

Arithmetic operations : Perform mathematical calculations on corresponding elements of NumPy arrays.

In [85]:
# Relational \ (  a2 < > == =! >= <= )

a2 < 20


array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [False, False, False, False]])

Relational operations : compare corresponding elements of NumPy arrays and return True or False

In [86]:
#  Vector Operation  \ ( a1 + - * / % ** a2)
# Arthmetic
a1 + a2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

Vector Operation : Performs element-wise operations between two NumPy arrays of the same size and shape

-------------------------------------------
Array Functions

---------------------------------------

In [87]:
a1 = np.random.random((3,3))
a1 = np.round(a1*10)

a1

array([[ 5.,  6., 10.],
       [ 3.,  4., 10.],
       [ 1.,  1.,  3.]])

round means range like upto whatever number

In [88]:
# np max/min/prod/sum
# 0 -> col and 1 -> row (it will check the maximum number )
np.max(a1,axis=0)


array([ 5.,  6., 10.])

In [89]:
# Trigonmetric \ ( np. sin cos tan )
np.sin(a1)

array([[-0.95892427, -0.2794155 , -0.54402111],
       [ 0.14112001, -0.7568025 , -0.54402111],
       [ 0.84147098,  0.84147098,  0.14112001]])

In [90]:
# Dot \ ( np.dot a2,a3 )
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

np.dot (a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [91]:
# log and exponential
print(np.log(a1))


print(np.exp(a1))

[[1.60943791 1.79175947 2.30258509]
 [1.09861229 1.38629436 2.30258509]
 [0.         0.         1.09861229]]
[[1.48413159e+02 4.03428793e+02 2.20264658e+04]
 [2.00855369e+01 5.45981500e+01 2.20264658e+04]
 [2.71828183e+00 2.71828183e+00 2.00855369e+01]]


In [92]:
print(np.floor(a1))
print(np.ceil(a1))


[[ 5.  6. 10.]
 [ 3.  4. 10.]
 [ 1.  1.  3.]]
[[ 5.  6. 10.]
 [ 3.  4. 10.]
 [ 1.  1.  3.]]


np.floor(): Rounds each element down to the nearest integer.


np.ceil(): Rounds each element up to the nearest integer.

---------------------------
Indexing & Slicing

---------------------

In [93]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(27).reshape(3,3,3)

print(a1)
print(a2)
print(a3)

[0 1 2 3 4 5 6 7 8 9]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [94]:

a1[-1]

np.int64(9)

In [95]:
a2[0,2]

np.int64(2)

In [96]:
a3


array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [97]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Indexing Or Slicing Left mood nhi tha 😜


Iteration ka be smj nhi aaya


-------------------
Iteration

--------------------------------


In [98]:
a1


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [99]:
for i in a1:
  print(i)

0
1
2
3
4
5
6
7
8
9


In [100]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [101]:
for i in a2:
  print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [102]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [103]:
for i in a3:
  print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


Iteration: The process of accessing or visiting each element of a NumPy array one by one.

In [104]:
for i in np.nditer(a3):
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


-----------------------------
Reshaping

-----------------------------------

In [105]:
# reshape
# we did eariler

In [106]:
# Trarnspose | ( np.transpose or a2.T )

np.transpose(a2)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

-----------------------------
Stacking

-----------------------------

In [107]:
# Horizontal Stacking
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)

np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [108]:
# Vertical Stacking

np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

Stacking : Make sure one thing both both array has same size

---------------------------------------
Splitting

--------------------------------


In [109]:
# Horizontal Split | ( np.hsplit(a4,number of division ))
a4
np.hsplit(a4,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [110]:
# Vertical Split  | ( np.vsplit(a5,3 ))
np.vsplit(a5,3)

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]

In: horizontal it cut vertical and in vertical it cut horizontal

and in verical it can't divide with 2

--------------------------------
Video 2 Advanced Numpy         -
                               -
--------------------------------

In [111]:
import numpy as np


-------------------------------
Fancy Indexing & Boolean Indexing

----------------------------------

In [120]:
a = np.arange(16).reshape(4,4)
a[[0,2]]


array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11]])