<a href="https://colab.research.google.com/github/Pritishcoder07/BasicML/blob/main/NUMPY.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NUMPY


----------------------------------
NumPy Creation & Initializing

---------------------------------

In [7]:
# IMPORT NUMPY AS NP
import numpy as np

In [8]:
# import dataset 1D Array |  1D Array is also know as Vector
a = np.array([1,5,2,1])
print((a))

[1 5 2 1]


Q. Using numpy array in the front of list

A. Because perform all NumPy operations efficiently, use a NumPy array, not a regular Python list.

In [9]:
# import dataset 2D Array | 2D Array is also know as Matrix
b = np.array([[1,5,6,2],[1,5,6,2]])
print(b)


[[1 5 6 2]
 [1 5 6 2]]


In [10]:
# import dataset 3D Array or Higher Array \ 3D Array or Higher Array is konw as tensor
c = np.array([[[1,1,1,1],[1,1,1,2]],[[1,1,1,3],[1,1,1,4]]])
print(c)

[[[1 1 1 1]
  [1 1 1 2]]

 [[1 1 1 3]
  [1 1 1 4]]]


In [11]:
# Data Type \ ( dtype )
A = np.array([5,9,6,3,5],dtype=int)
B = np.array([5,9,6,3,5],dtype=float)
C = np.array([5,9,6,3,5],dtype=str)
D = np.array([5,9,6,3,5],dtype=bool)
E = np.array([5,9,6,3,5],dtype=complex)
print(A)
print(B)
print(C)
print(D)
print(E)


[5 9 6 3 5]
[5. 9. 6. 3. 5.]
['5' '9' '6' '3' '5']
[ True  True  True  True  True]
[5.+0.j 9.+0.j 6.+0.j 3.+0.j 5.+0.j]


see i can change the datatype of array to any datatype

In [12]:
# Data Arange
A = np.arange(1,11)
print(A)


[ 1  2  3  4  5  6  7  8  9 10]


In [13]:
B = np.arange(1,100,5)
print(B)

[ 1  6 11 16 21 26 31 36 41 46 51 56 61 66 71 76 81 86 91 96]


Cell 1 -> arange: Creates a NumPy array with evenly spaced values within a specified range.

Cell 2 -> it is written (1,100,5) The 5 after 100 means the gap between the numbers


In [14]:
# Data Resape
A = np.arange(1,11).reshape(2,5)
print(A)
B = np.arange(1,13).reshape(3,4)
print(B)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


Reshape : Changes the shape (dimensions) of a NumPy array without changing its data. it's vaild only reshape like (2,5),(3,5) like multiple vaild only

In [15]:
# ONES \ ( np.ones )
A = np.ones((3,4))
print(A)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


All Cell baiscally for initializing the value without any think for Neural Network

Cell 1 -> Ones : Creates a NumPy array filled with 1s.

In [16]:
# Zeros \ ( np.zeros )
A = np.zeros((3,4))
print(A)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


Cell 2 -> Zeros : Creates a NumPy array filled with 0s.


In [17]:
# Random \  (np.random.random )
A = np.random.random((3,4))
print(A)

[[0.83685635 0.42885753 0.58156898 0.06479698]
 [0.82601838 0.7156975  0.67886813 0.26211145]
 [0.80233347 0.183508   0.07936639 0.34837568]]


Cell 3 -> Random : Creates a NumPy array with random values between 0 and 1

In [18]:
# linespace \ ( np.linspace )
A = np.linspace(1,15,9)
print(A)

[ 1.    2.75  4.5   6.25  8.    9.75 11.5  13.25 15.  ]


Linspace : Creates a NumPy array with evenly spaced values between a start and an end value. After the 15 9 means total number you will seprate


In [19]:
# Indetity \ ( np.indetity )
A = np.identity(5)
print(A)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


Identity : Creates an identity matrix with 1s on the main diagonal and 0s elsewhere.

## Summary of NumPy Operations

This notebook provides an introduction to fundamental NumPy array creation and manipulation techniques:

*   **Array Creation:**
    *   `np.array()`: Used to create 1D (vectors), 2D (matrices), and higher-dimensional arrays (tensors) from Python lists.
    *   `dtype`: Allows explicit specification of data types for array elements (e.g., `int`, `float`, `str`, `bool`, `complex`).
    *   `np.arange()`: Creates arrays with evenly spaced values within a given range, with an optional step size.
    *   `np.linspace()`: Creates arrays with a specified number of evenly spaced values between a start and end point.

*   **Special Array Initialization:**
    *   `np.ones()`: Creates arrays filled with ones.
    *   `np.zeros()`: Creates arrays filled with zeros.
    *   `np.random.rand()`: Creates arrays with random values between 0 and 1.
    *   `np.identity()`: Creates an identity matrix (square matrix with ones on the main diagonal and zeros elsewhere).

*   **Array Manipulation:**
    *   `.reshape()`: Changes the shape (dimensions) of an array without altering its data, provided the total number of elements remains the same.

In [20]:
print("HI")

HI


-------------------------------------------
NumPy Attributes

-------------------------------------------

In [21]:
a1 = np.arange(10)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

print(a1)
print(a2)
print(a3)

[0 1 2 3 4 5 6 7 8 9]
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [22]:
# ndim \ ( ndim )

a1 = np.arange(10)
a1.ndim


1

Ndim : Returns the number of dimensions (axes) of a NumPy array.

In [23]:
# shape \ ( shape )

a1 = np.arange(10)
a2.shape

(3, 4)

In [24]:
a3.shape

(2, 2, 2)

Shape: Returns the shape (rows, columns, and dimensions) of a NumPy array.

(2, 2, 2) → 2 Dimension , each containing 2 rows and 2 columns.

In [25]:
# size \ ( size )
a1 = np.arange (10)
a1.size

10

Size: Returns the total number of elements in a NumPy array.

In [26]:
# itemsize \ ( itemsize )

a1 = np.arange(10)
a1.itemsize

8

Itemsize: Returns the size of each element in a NumPy array in bytes.

In [27]:
# dtypw \ ( dtype )

a1 = np.arange(10)
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int64
float64
int64


Dtype: Returns the data type of the elements in a NumPy array.

---------------------------------------------------------
Changing Datatype

--------------------------------------------------------

In [28]:
# Change Datatype \ ( as.type )

a1 = np.arange(10)
a1.astype(np.int32)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)

---------------------------
Arithmetic operations

---------------------------

In [31]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

print(a1)

print(a2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
