<a href="https://colab.research.google.com/github/Pritishcoder07/BasicML/blob/main/NUMPY.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NUMPY


In [1]:
# IMPORT NUMPY AS NP
import numpy as np

In [2]:
# import dataset 1D Array |  1D Array is also know as Vector
a = np.array([1,5,2,1])
print((a))

[1 5 2 1]


Q. Using numpy array in the front of list

A. Because perform all NumPy operations efficiently, use a NumPy array, not a regular Python list.

In [3]:
# import dataset 2D Array | 2D Array is also know as Matrix
b = np.array([[1,5,6,2],[1,5,6,2]])
print(b)


[[1 5 6 2]
 [1 5 6 2]]


In [4]:
# import dataset 3D Array or Higher Array \ 3D Array or Higher Array is konw as tensor
c = np.array([[[1,1,1,1],[1,1,1,2]],[[1,1,1,3],[1,1,1,4]]])
print(c)

[[[1 1 1 1]
  [1 1 1 2]]

 [[1 1 1 3]
  [1 1 1 4]]]


In [5]:
# Data Type \ ( dtype )
A = np.array([5,9,6,3,5],dtype=int)
B = np.array([5,9,6,3,5],dtype=float)
C = np.array([5,9,6,3,5],dtype=str)
D = np.array([5,9,6,3,5],dtype=bool)
E = np.array([5,9,6,3,5],dtype=complex)
print(A)
print(B)
print(C)
print(D)
print(E)


[5 9 6 3 5]
[5. 9. 6. 3. 5.]
['5' '9' '6' '3' '5']
[ True  True  True  True  True]
[5.+0.j 9.+0.j 6.+0.j 3.+0.j 5.+0.j]


see i can change the datatype of array to any datatype

In [6]:
# Data Arange
A = np.arange(1,11)
print(A)


[ 1  2  3  4  5  6  7  8  9 10]


In [7]:
B = np.arange(1,100,5)
print(B)

[ 1  6 11 16 21 26 31 36 41 46 51 56 61 66 71 76 81 86 91 96]


Cell 1 -> arange: Creates a NumPy array with evenly spaced values within a specified range.

Cell 2 -> it is written (1,100,5) The 5 after 100 means the gap between the numbers


In [27]:
# Data Resape
A = np.arange(1,11).reshape(2,5)
print(A)
B = np.arange(1,13).reshape(3,4)
print(B)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


Reshape : Changes the shape (dimensions) of a NumPy array without changing its data. it's vaild only reshape like (2,5),(3,5) like multiple vaild only