<a href="https://colab.research.google.com/github/Pritishcoder07/BasicML/blob/main/NUMPY.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NUMPY


In [7]:
# IMPORT NUMPY AS NP
import numpy as np

In [15]:
# import dataset 1D Array |  1D Array is also know as Vector
a = np.array([1,5,2,1])
print((a))

[1 5 2 1]


In [16]:
# import dataset 2D Array | 2D Array is also know as Matrix
b = np.array([[1,5,6,2],[1,5,6,2]])
print(b)


[[1 5 6 2]
 [1 5 6 2]]
[[[1 5 6 2]
  [1 5 6 2]]

 [[1 5 6 2]
  [1 5 6 2]]]


In [19]:
# import dataset 3D Array or Higher Array \ 3D Array or Higher Array is konw as tensor
c = np.array([[[1,1],[1,2]],[[1,3],[1,4]]])
print(c)

[[[1 1]
  [1 2]]

 [[1 3]
  [1 4]]]
